"""
Data models for the Multi-Agent Deep Researcher system.
"""

from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime
from enum import Enum


class SourceType(str, Enum):
    """Types of information sources."""
    ACADEMIC = "academic"
    NEWS = "news"
    REPORT = "report"
    API = "api"
    WEB = "web"
    DOCUMENT = "document"


class Source(BaseModel):
    """A single information source."""
    title: str
    url: str
    source_type: SourceType
    snippet: str
    relevance_score: float = 0.0
    published_date: Optional[str] = None
    author: Optional[str] = None
    content: Optional[str] = None  # Full text content for uploaded documents

    def __str__(self):
        return f"[{self.source_type.upper()}] {self.title} ({self.url})"


class Finding(BaseModel):
    """A research finding from one or more sources."""
    claim: str
    supporting_sources: list[str] = Field(default_factory=list)
    confidence: float = 0.0
    contradictions: list[str] = Field(default_factory=list)
    metadata: dict = Field(default_factory=dict)


class Insight(BaseModel):
    """An insight generated by reasoning over findings."""
    insight: str
    reasoning_chain: list[str]
    supporting_findings: list[str] = Field(default_factory=list)
    confidence: float = 0.0
    category: str = "general"


class Contradiction(BaseModel):
    """A contradiction between sources."""
    claim_a: str
    source_a: str
    claim_b: str
    source_b: str
    resolution: Optional[str] = None


class ResearchReport(BaseModel):
    """The final compiled research report."""
    title: str
    query: str
    executive_summary: str
    findings: list[Finding] = Field(default_factory=list)
    insights: list[Insight] = Field(default_factory=list)
    contradictions: list[Contradiction] = Field(default_factory=list)
    sources: list[Source] = Field(default_factory=list)
    recommendations: list[str] = Field(default_factory=list)
    generated_at: datetime = Field(default_factory=datetime.now)

    def to_markdown(self) -> str:
        """Convert report to markdown format."""
        md = f"# {self.title}\n\n"
        md += f"**Research Query:** {self.query}\n\n"
        md += f"**Generated:** {self.generated_at.strftime('%Y-%m-%d %H:%M')}\n\n"
        md += "---\n\n"

        md += "## Executive Summary\n\n"
        md += f"{self.executive_summary}\n\n"
        md += "---\n\n"

        if self.findings:
            md += "## Key Findings\n\n"
            for i, finding in enumerate(self.findings, 1):
                md += f"### Finding {i}: {finding.claim}\n\n"
                md += f"- **Confidence:** {finding.confidence:.0%}\n"
                md += f"- **Sources:** {', '.join(finding.supporting_sources)}\n"
                if finding.contradictions:
                    md += f"- **Contradictions:** {len(finding.contradictions)} noted\n"
                md += "\n"

        if self.insights:
            md += "## Generated Insights\n\n"
            for i, ins in enumerate(self.insights, 1):
                md += f"### Insight {i}: {ins.insight}\n\n"
                md += f"**Reasoning:** {' → '.join(ins.reasoning_chain)}\n\n"
                md += f"**Confidence:** {ins.confidence:.0%}\n\n"
                md += f"**Category:** {ins.category}\n\n"

        if self.contradictions:
            md += "## Contradictions & Conflicts\n\n"
            for i, c in enumerate(self.contradictions, 1):
                md += f"### Conflict {i}\n\n"
                md += f"- **Claim A:** {c.claim_a} (Source: {c.source_a})\n"
                md += f"- **Claim B:** {c.claim_b} (Source: {c.source_b})\n"
                if c.resolution:
                    md += f"- **Resolution:** {c.resolution}\n"
                md += "\n"

        if self.recommendations:
            md += "## Recommendations\n\n"
            for i, rec in enumerate(self.recommendations, 1):
                md += f"{i}. {rec}\n"
            md += "\n"

        if self.sources:
            doc_sources = [s for s in self.sources if s.source_type == SourceType.DOCUMENT]
            other_sources = [s for s in self.sources if s.source_type != SourceType.DOCUMENT]

            if doc_sources:
                md += "## Uploaded Documents\n\n"
                for i, source in enumerate(doc_sources, 1):
                    md += f"### {i}. {source.title}\n\n"
                    if source.content:
                        preview = source.content[:3000]
                        if len(source.content) > 3000:
                            preview += f"\n\n... (truncated, total {len(source.content)} characters)"
                        md += f"{preview}\n\n"
                    md += "---\n\n"

            if other_sources:
                md += "## External Sources\n\n"
                for i, source in enumerate(other_sources, 1):
                    md += f"{i}. **{source.title}** — [{source.url}]({source.url})\n"
                md += "\n"

        return md
